name: online-photo-album-deployment

on:
    push:
        branches:
            - main

jobs:
    run-tests:
        name: run-tests
        runs-on: ubuntu-latest
        services:
          postgres:
            image: postgres:13
            ports:
              - 5432:5432
            env:
              POSTGRES_PASSWORD: postgres
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"
            - name: Run Make
              env: 
                POSTGRES_USER: ${{ secrets.DB_USER }}
                POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
                POSTGRES_NAME: ${{ secrets.DB_NAME }}
                POSTGRES_PORT: 5432
                POSTGRES_HOST: localhost
              run: | 
                make requirements
                make checks-setup
                make run-checks

    deploy-infrastructure:
        name: deploy-infrastructure
        runs-on: ubuntu-latest
        environment: prod
        needs: run-tests
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4.1.0
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}
            - name: Install Terraform
              uses: hashicorp/setup-terraform@v3
            - name: Terraform Init
              working-directory: terraform
              run: terraform init
            - name: Terraform Apply
              working-directory: terraform
              run: terraform apply -auto-approve



