name: pull-request-check

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - main

jobs:
    setup-and-tests:
        name: setup-and-tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"
            - name: Run Make
              run: | 
                make requirements
                make checks-setup
                make security-test
                make run-black
                make check-coverage
            - name: run-tests
              run: make run-tests


    check-infrastructure:
        name: check-infrastructure
        runs-on: ubuntu-latest
        environment: prod
        needs: setup-and-tests
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4.1.0
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}
            - name: Install Terraform
              uses: hashicorp/setup-terraform@v3
            - name: Terraform Init
              working-directory: terraform
              run: terraform init
            - name: Terraform Plan
              working-directory: terraform
              run: terraform plan
